#  Copyright 2026 Filippo Savi
#  Author: Filippo Savi <filssavi@gmail.com>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Resolves the current git commit id and writes it into a header.
# The commit is baked at build time so the installed binary reports
# correctly without a .git directory present.
#
# Usage:
#   cmake -DSOURCE_DIR="<repository root>"
#         -DOUTPUT="<generated header path>"
#         -P get_git_commit.cmake

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "get_git_commit.cmake requires SOURCE_DIR and OUTPUT")
endif()

set(COMMIT_ID "UNKNOWN")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C "${SOURCE_DIR}" rev-parse --short HEAD
        OUTPUT_VARIABLE COMMIT_ID
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_RESULT
    )
    if(NOT GIT_RESULT EQUAL 0 OR COMMIT_ID STREQUAL "")
        set(COMMIT_ID "UNKNOWN")
    endif()
endif()

string(CONCAT HEADER_CONTENT
"// Generated by cmake/get_git_commit.cmake. Do not edit.\n"
"#ifndef ANANKE_VERSION_HPP\n"
"#define ANANKE_VERSION_HPP\n"
"\n"
"#define ANANKE_COMMIT_ID \"${COMMIT_ID}\"\n"
"\n"
"#endif //ANANKE_VERSION_HPP\n")

# Only touch the file when the content changed to avoid needless rebuilds.
set(NEEDS_WRITE TRUE)
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" EXISTING_CONTENT)
    if(EXISTING_CONTENT STREQUAL HEADER_CONTENT)
        set(NEEDS_WRITE FALSE)
    endif()
endif()
if(NEEDS_WRITE)
    file(WRITE "${OUTPUT}" "${HEADER_CONTENT}")
    message(STATUS "Ananke commit id: ${COMMIT_ID}")
endif()
